#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : robin-map
Version  : 0.6.3
Release  : 1
URL      : https://github.com/Tessil/robin-map/archive/v0.6.3/robin-map-0.6.3.tar.gz
Source0  : https://github.com/Tessil/robin-map/archive/v0.6.3/robin-map-0.6.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: robin-map-data = %{version}-%{release}
Requires: robin-map-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-cmake

%description
[![Build Status](https://travis-ci.org/Tessil/robin-map.svg?branch=master)](https://travis-ci.org/Tessil/robin-map) [![Build status](https://ci.appveyor.com/api/projects/status/lo79n4ya4nta79q4/branch/master?svg=true)](https://ci.appveyor.com/project/Tessil/robin-map/branch/master)

%package data
Summary: data components for the robin-map package.
Group: Data

%description data
data components for the robin-map package.


%package dev
Summary: dev components for the robin-map package.
Group: Development
Requires: robin-map-data = %{version}-%{release}
Provides: robin-map-devel = %{version}-%{release}
Requires: robin-map = %{version}-%{release}

%description dev
dev components for the robin-map package.


%package license
Summary: license components for the robin-map package.
Group: Default

%description license
license components for the robin-map package.


%prep
%setup -q -n robin-map-0.6.3
cd %{_builddir}/robin-map-0.6.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1614623242
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1614623242
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/robin-map
cp %{_builddir}/robin-map-0.6.3/LICENSE %{buildroot}/usr/share/package-licenses/robin-map/e0d5bca8b8d5aa09d739b5956b93e16f477f14d9
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/cmake/*

%files dev
%defattr(-,root,root,-)
/usr/include/tsl/robin_growth_policy.h
/usr/include/tsl/robin_hash.h
/usr/include/tsl/robin_map.h
/usr/include/tsl/robin_set.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/robin-map/e0d5bca8b8d5aa09d739b5956b93e16f477f14d9
