#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : robin-map
Version  : 1.0.1
Release  : 2
URL      : https://github.com/Tessil/robin-map/archive/v1.0.1/robin-map-1.0.1.tar.gz
Source0  : https://github.com/Tessil/robin-map/archive/v1.0.1/robin-map-1.0.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: robin-map-data = %{version}-%{release}
Requires: robin-map-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-cmake

%description
[![CI](https://github.com/Tessil/robin-map/actions/workflows/ci.yml/badge.svg?branch=master)](https://github.com/Tessil/robin-map/actions/workflows/ci.yml)

%package data
Summary: data components for the robin-map package.
Group: Data

%description data
data components for the robin-map package.


%package dev
Summary: dev components for the robin-map package.
Group: Development
Requires: robin-map-data = %{version}-%{release}
Provides: robin-map-devel = %{version}-%{release}
Requires: robin-map = %{version}-%{release}

%description dev
dev components for the robin-map package.


%package license
Summary: license components for the robin-map package.
Group: Default

%description license
license components for the robin-map package.


%prep
%setup -q -n robin-map-1.0.1
cd %{_builddir}/robin-map-1.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672199337
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1672199337
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/robin-map
cp %{_builddir}/robin-map-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/robin-map/e0d5bca8b8d5aa09d739b5956b93e16f477f14d9
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/cmake/*

%files dev
%defattr(-,root,root,-)
/usr/include/tsl/robin_growth_policy.h
/usr/include/tsl/robin_hash.h
/usr/include/tsl/robin_map.h
/usr/include/tsl/robin_set.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/robin-map/e0d5bca8b8d5aa09d739b5956b93e16f477f14d9
